# Generated by Django 5.1.15 on 2026-09-21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoistureBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch_no", models.CharField(max_length=40)),
                ("open_date", models.DateField(default=django.utils.timezone.localdate)),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("greenhouse", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="moisture_batches", to="core.greenhouse")),
            ],
            options={
                "ordering": ["-open_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MoistureReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("moisture_pct", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(95)])),
                ("sampled_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="readings", to="core.moisturebatch")),
                ("zone", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="moisture_readings", to="core.zone")),
            ],
            options={
                "ordering": ["batch_id", "zone__zone_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="moisturebatch",
            constraint=models.UniqueConstraint(fields=("greenhouse", "batch_no"), name="uniq_moisture_batch_no_per_greenhouse"),
        ),
        migrations.AddConstraint(
            model_name="moisturereading",
            constraint=models.UniqueConstraint(fields=("batch", "zone"), name="uniq_moisture_reading_zone_per_batch"),
        ),
        migrations.AddConstraint(
            model_name="moisturereading",
            constraint=models.CheckConstraint(check=models.Q(("moisture_pct__gte", 5), ("moisture_pct__lte", 95)), name="moisture_reading_pct_between_5_95"),
        ),
    ]
